[package]
name = "asset_shader_source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Validating shaders
naga = { version = "*", features = ["wgsl-in", "validate", "span"] }
